services:
  nesd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${NESD_CONTAINER_NAME:-nesd}
    restart: unless-stopped
    network_mode: host
    environment:
      - ENV=${ENV:-PRODUCTION}
      - NESD_LISTEN_ADDR=${NESD_LISTEN_ADDR:-}
    volumes:
      - ./runtime:/data
      - ./tests:/tests:ro
